config/routes.rb
Trunk::Application.routes.draw do
  root :to => 'user_sessions#login'
  
  match 'login' => "user_sessions#login",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'tests_normal_show/:id' => "tests#tests_normal_show", :as => "tests_normal_show" ,:via => :get
  match'forgot_password'=>'signup#forgot_password',:as=> "forgot_password" ,:via =>[:get,:post]
  match'reset_password'=>'signup#reset_password',:as =>"reset_password" ,:via =>[:get,:post]
   match'graph'=>'samgruffs#index',:as=>"graph",:via=>:get
  match'report'=>'responses#report',:as=> "report" ,:via => :put
  match 'samgruffs/graph_code' => "samgruffs#graph_code", :via => :get
  match 'samgruffs/index' => "samgruffs#index", :via => :get
  resources :signup
  resources :users
  resources :user_sessions
  resources :tests do
    resources :questions do
      resources :answers
    end
  end
  resources :categories

  resources :reponses

  

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to  :test
  has_many  :answers
  # has_many :responses
 has_and_belongs_to_many :responses
  

validates :question,:type_of_question, :presence => true
 
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @initial_question_number  = 0
    @test = Test.find_by_id(params[:test_id])
    @question = @test.questions.build
  end

  def create
    correct_answer = params[:correct_answer][:string]
    @initial_question_number  = params[:next][:number].to_i
    @test = Test.find_by_id(params[:test_id])
    if@initial_question_number <= @test.no_of_questions
      @initial_question_number +=1
      @question = @test.questions.build(params[:question])      
      Question.transaction do
        @question.user_id=current_user.id
        @question.correct_answer = correct_answer        
        @question.save
        if @initial_question_number-1 == @test.no_of_questions
          @test.state="active"
        @test.save
        end
        if @question.type_of_question =="text"          
            @question.correct_answer=params[:corrct_text_answer];          
          @question.answers.create(:answer=>" ")
        else
          params[:answers].reject(&:blank?).each do |a|
            @question.answers.create(:answer=>a)
          end
        end
      end
      @question.user_id=current_user.id
    @question.save
    else
      redirect_to questions_path
    end
  end

  def edit
    @initial_question_number  = 0
    @test = Test.find_by_id(params[:id])
    @question = @test.questions.first
  end

  def update
    @initial_question_number  = params[:next][:number].to_i

    @test = Test.find_by_id(params[:test_id])
    @question = @test.questions.find(params[:id])
    @question.update_attributes(params[:question])

    # @question1=Question.find_by_id(params[:question_id])
    # @answer=@question1.answers.find(params[:id])
    # @answer.update_attributes(params[:answer])

    @initial_question_number +=1
  # if @initial_question_number-1 == @test.no_of_questions
  # @test.state="active"
  # @test.update_attribute(:state)
  # end

  #   redirect_to questions_path
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_url
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answers.html.erb
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="text/javascript">
		$(document).ready(function() {
			var sel;			
			var arr = [];
			jQuery.noConflict();

			$('.del').live('click',function(){
					$(this).parent().parent().remove();
				});

				$('.add').die('click').live('click',function(){
					$(this).val('Delete');
					$(this).attr('class','del');
					var appendTxt = "<tr><td><input type='text' name='answers[]' /> <input type='checkbox'   name='check[]'/></td> <td><input type='button' class='add' value='Add More' /></td></tr>";
					$("tr:last").after(appendTxt);
				});
				

			// for disabling options table for type text
			$("#question_type_of_question").change(function() {
				sel = $("#question_type_of_question option:selected").text();
				if(sel == 'text') {
					$('#options-table').hide();
					$('#correct_ans_div').append("<br /><label for='corrct_text_answer'>Correct Answer :</label> <input type='text' id='corrct_text_answer' name='corrct_text_answer'/>");
				} else {
					uncheckAll();
					$('#options-table').show();
					$('#correct_ans_div').empty();
				}
			}).change();

			// for saving options
			$(".create_ques").click(function() {
				sel = $("#question_type_of_question option:selected").text();

				$('input[type=checkbox]:checked').each(function() {
					var m = $(this).prev().val();
					//jQuery.removeData(var, "arr");
					arr.push(m);
				})
				$('#correct_answer_string').val(arr);

			});

			
			
			// for saving correct answer
			$('#new_question').submit(function() {
                          var count= 0;
                                 $("#options-table").find("input:text").each(function(i) {
                                 $(this).val() == "" && sel != "text" ? count+=1 : count=0 ;
                                 });
                                 if(count>0)
                                   {
                                     alert("Option Cannot Be Empty");
                                     return false;
                                    }
                           var hidden_values = $('#correct_answer_string').val();

				if(hidden_values == "" && sel != "text") {
					alert("Please select the correct answer");
					return false;
				}
			});
			
			
			// for radio buttons			
			function uncheckAll() {
				$("#options-table").find("input:checkbox").each(function(i) {
					$(this).attr("checked", false);
				});
			}			
			$("#options-table").find("input:checkbox").live("change", function() {
				tickOnlyOne(this);
			});
			function tickOnlyOne(e) {
				if(sel == "radio") {
					uncheckAll();
					$(e).attr("checked", "checked");
				}
			}
			

		});

	</script>
</head>
<div class="field">
	<table id="options-table">
		<tr>
			<td>Enter answers</td>
		</tr>
		<tr>
			<td>
			<input type="text"   name="answers[]" />
			<input type="checkbox"   name="check[]"/>
			</td>
			<td>
			<input type="button" class="add" value="Add More" />
			</td>
		</tr>
	</table>
	<%= hidden_field(:correct_answer,:string ,:value=>'correct_answer' ) %>
</div>

app/views/questions/_form.html.erb
<%= form_for [@test,Question.new],:remote=>true do |f| %>
<% if @question.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@question.errors.count, "error") %> prohibited this test from being saved:</h2>
	<ul>
		<% @question.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<br />
<br />
Questions in current Test :
<% snum=0%>
<br />
<br />
<table id="table_questions">
	<tr>
		<th>S.No</th><th>Question</th><th>options</th>
	</tr>
	<% for questions in @test.questions%>
	<tr>
		<td><%= snum+1%></td>
		<% snum= snum+1%> <td><%= h questions.question %></td>
		<td> 
		<ol type="1">
                  <% for answers in questions.answers%>
			<li>
				<%= h answers.answer%>
			</li>
                        <% end %>
		</ol>

                </td>
	</tr>
	<% end %>
</table>
<% next_question = @initial_question_number== 0 ? 0+1 : number %>
<%= hidden_field(:next,:number ,:value=> next_question ) %>

Enter Question Number : <%= next_question  %>
<br/>
<br/>
<div class="field">
	<%= f.label :type_of_question %>
	<br />
	<%= f.collection_select :type_of_question,Choice.all,:name,:name,{:prompt=>true} %>
</div>
<div class="field">
	<%= f.label :question %>
	<br />
	<%= f.text_field :question %>
</div>
<div id="correct_ans_div"></div>
<%= render 'answers' %>
<div class="actions">
	<%= f.submit :class => 'create_ques'  %>
</div>
<% end %>

app/views/questions/_questions2.html.erb
<% @question = @initial_question_number==0  ? @question : question %>
<%= form_for  [@test,@question],:remote=>true do |f| %>
<div class="field">
  <%= f.label :type_of_question %><br />
    <%= f.collection_select :type_of_question,Choice.all,:name,:name,{:prompt=>true} %>
  </div>
  <div class="field">
    <%= f.label :question %><br />
    <%= f.text_field :question %>
  </div>
 <%= hidden_field(:next,:number ,:value=> @initial_question_number ) %>

<%= render 'answers' %>
  <div class="actions">
    <%= f.submit  %>
  </div>
<% end %>

app/views/questions/_test_details.html.erb
<head>
<style type="text/css">
table
{
border:1px dotted #000;
}
td, th
{
   padding: 3px 10px;
border:1px dotted #000;
}
</style>
</head>

<table>
  <tr>
    <td>
      Test Name
    </td>
    <td>
      Number of Questions
    </td>
    <td>
      Test Category Name
    </td>

  </tr>
    <tr>
    <td>
      <%=  @test.name%>
    </td>
    <td>
       <%=  @test.no_of_questions%>
    </td>
    <td>
     <%=  @test.category.name unless  @test.category.blank? %>
    </td>

  </tr>
</table>

app/views/questions/create.js.erb
<%  if @initial_question_number <= @test.no_of_questions %>
  $("#next-question").html("<%= escape_javascript(render :partial=>'questions/form',:locals=>{:number=>@initial_question_number}) %>")
<% elsif @initial_question_number = @test.no_of_questions  %>  
  $(window.location.replace("/tests"))
<% end %>

app/views/questions/edit.html.erb
<h1>Add Test Questions</h1>
<div id="test-details">
  <%= render "test_details" %>
</div>
<div id="next-question">
  <%= render 'questions2' %>  
</div>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Question</th>
    <th>Test name</th>
    <th>Choice type</th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.question %></td>
    <td><%= question.test_id %></td>
    <td><%= question.type_of_question %></td>
    <td><%= link_to 'Show', test_question_path(question) %></td>
    <td><%= link_to 'Edit', edit_test_question_path(question) %></td>
    <td><%= link_to 'Destroy', test_question_path(question), :confirm=> 'Are you sure?', :method=> :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%#= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>Add Test Questions</h1>
<div id="test-details">
  <%= render "test_details" %>
</div>
<div id="next-question">
  <%= render 'form' %>
</div>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <b>Q:</b>
  <%= @question.question %>
<br />

  <b>Help text:</b>
  <%= @question.help_text %>
</p>

<ul>
    <% for answers in @question.answers%>
      <li><%= h answers.answer%></li>
    <% end %>
  </ul>

<%= link_to 'Edit', edit_question_path(@question) %>
<%= link_to "Destroy", @test, :confirm => 'Are you sure?', :method => :delete %> 
<%= link_to "View All", questions_path %>

app/views/questions/update.js.erb
<%  @test.questions.each_with_index do |q,i|
      if @initial_question_number == i
        @question = q
      end
    end %>
<%  if @initial_question_number < @test.no_of_questions %>
  $("#next-question").html("<%= escape_javascript(render :partial=>'questions/questions2',:locals=>{:question=>@question,:number=>@initial_question_number}) %>")
<% elsif @initial_question_number = @test.no_of_questions  %>
			
			<% @test.state="active" %>
            <% @test.save %>

  $(window.location.replace("/tests"))
<% end %>