config/routes.rb
Trunk::Application.routes.draw do
  root :to => 'user_sessions#login'
  
  match 'login' => "user_sessions#login",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'tests_normal_show/:id' => "tests#tests_normal_show", :as => "tests_normal_show" ,:via => :get
  match'forgot_password'=>'signup#forgot_password',:as=> "forgot_password" ,:via =>[:get,:post]
  match'reset_password'=>'signup#reset_password',:as =>"reset_password" ,:via =>[:get,:post]
   match'graph'=>'samgruffs#index',:as=>"graph",:via=>:get
  match'report'=>'responses#report',:as=> "report" ,:via => :put
  match 'samgruffs/graph_code' => "samgruffs#graph_code", :via => :get
  match 'samgruffs/index' => "samgruffs#index", :via => :get
  resources :signup
  resources :users
  resources :user_sessions
  resources :tests do
    resources :questions do
      resources :answers
    end
  end
  resources :categories

  resources :reponses

  

end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
skip_before_filter :require_user 

  layout false
  def new
    @user= User.new
  end

  def create
    
    @user=User.new(params[:user])
  
    @user.role_id = 3
    # @user.created_user_id = current_user.id
    # current_user.is_admin? ? "2" : "
    if@user.save
      flash[:notice]="Account registered"
      redirect_to root_path
    else
      render "new"
    end
  end

  def forgot_password
    if request.post?
      @user = User.find_by_email(params[:email])
      if @user
        redirect_to :action =>"reset_password",:email => @user.email
      else
        render :text=>"reset_password"
      end
    end
  end

  def reset_password   
    @user =User.find_by_email(params[:email])
    if request.post? and params[:user]
      @user.password = params[:user][:password]
      @user.password_confirmation = params[:user][:password_confirmation]
      if @user.save
        redirect_to root_url
      else       
        render "reset_password"
      end
    end
    
  end
   def index
    if current_user.is_admin?    
      @users = User.where(:role_id => [1, 2])
    else    
      @users = User.where("role_id = ? and created_user_id= ?","3", current_user.id)
    end

  end

  
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/views/signup/_form.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<table>
        <tr>
                <td><%= form.label :first_name %></td>
                <td><%= form.text_field :first_name ,:placeholder=>" first name" %></td>
        </tr>
        <tr>
                <td><%= form.label :last_name %></td>
                <td><%= form.text_field :last_name ,:placeholder=>"lasr name" %></td>
        </tr>
        <tr>
                <td><%= form.label :email %></td>
                <td><%= form.text_field :email ,:placeholder=>"email" %></td>
        </tr>
        <tr>
                <td><%= form.label :phone_number %></td>
                <td><%= form.text_field :phone_number ,:placeholder=>"phone number" %></td>
        </tr>
        <tr>
                <td><%= form.label :password %></td>
                <td><%= form.password_field :password ,:placeholder=>"password" %></td>
        </tr>
        <tr>
                <td><%= form.label :password_confirmation %></td>
                <td><%= form.password_field :password_confirmation ,:placeholder=>"confirm password"%></td>
        </tr>
</table>

app/views/signup/forgot_password.html.erb
<html>
<head>
  <title>Sign up</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js", "signup", :media => "all" %>
  <%#= javascript_include_tag  :defaults,"signup","rails.validations.custom.js","jquery-1.7.1.js","tabs.js"%>
  <%#= javascript_include_tag :defaults,"application","rails.validations", "rails.validations.custom" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
<div id="header">
  <h1>Dynamic Form Builder</h1>
        </div>
  <div id="signup_main">

<h1>Forgot Password</h1>
<p>

  
    Please enter the email address you used to register.
  
</p>


  <%= form_tag  forgot_password_path do -%>
  <%= label_tag :Email %>
  <%= text_field_tag :email %><br/>
  <div><%= submit_tag 'Submit' %></div>
  <% end -%>
  
</div>
 </div>
</body>
</html>

app/views/signup/index.html.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%#= "index" %>

<h1>Listing users</h1>
<table  >
    <tr >
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>

        <th>
            Phone number
        </th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td>
            <%= user.first_name %>
        </td>
        <td>
            <%= user.last_name %>
        </td>
        <td>
            <%= user.email %>
        </td>
	<td>
	    <%= user.phone_number%>
	</td>
     </tr>
    <% end %>
</table>

app/views/signup/new.html.erb
<html>
<head>
  <title>Sign up</title>
  <%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.6.0/jquery.min.js", "signup", :media => "all" %>
  <%#= javascript_include_tag  :defaults,"signup","rails.validations.custom.js","jquery-1.7.1.js","tabs.js"%>
  <%#= javascript_include_tag :defaults,"application","rails.validations", "rails.validations.custom" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="wrapper">
<div id="header">
  <h1>Dynamic Form Builder</h1>
        </div>
  <div id="signup_main">

<h3> Registration Form</h3>
            <%= form_for :user ,:url=>signup_path  do |f| %>
            <%#= f.error_messages %>
            <%= render :partial => "form", :object => f %>
            <%= f.submit "Register" , :class=>'submit_btn' %>
            <% end %>
  </div>
 </div>
</body>
</html>

app/views/signup/reset_password.html.erb
<html>
<head>
  <title>Reset Password</title>
  <%= stylesheet_link_tag  "signup", :media => "all" %>
    <%= csrf_meta_tags %>
</head>
<body>


  <div id="wrapper"/>
<div id="header">
  <h1>Dynamic Form Builder</h1>
        </div>
  <div id="signup_main">
<%= form_for :user, :url => {:controller =>"signup" ,:action=>:reset_password}  do |f| %>


 
<%= hidden_field_tag :email,  current_user.nil? ?   @user.email : current_user.email  %>
<p>
<%= f.label :New_password %><br />
<%= f.password_field :password %>
</p>
<p>
<%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %>
</p>
<%= f.submit "Reset Password " %>
<% end %>
</div>
</body>
</html>