config/routes.rb
Trunk::Application.routes.draw do
  root :to => 'user_sessions#login'
  
  match 'login' => "user_sessions#login",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'tests_normal_show/:id' => "tests#tests_normal_show", :as => "tests_normal_show" ,:via => :get
  match'forgot_password'=>'signup#forgot_password',:as=> "forgot_password" ,:via =>[:get,:post]
  match'reset_password'=>'signup#reset_password',:as =>"reset_password" ,:via =>[:get,:post]
   match'graph'=>'samgruffs#index',:as=>"graph",:via=>:get
  match'report'=>'responses#report',:as=> "report" ,:via => :put
  match 'samgruffs/graph_code' => "samgruffs#graph_code", :via => :get
  match 'samgruffs/index' => "samgruffs#index", :via => :get
  resources :signup
  resources :users
  resources :user_sessions
  resources :tests do
    resources :questions do
      resources :answers
    end
  end
  resources :categories

  resources :reponses

  

end

app/models/admin_session.rb
class AdminSession < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base

#  validates :answer, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many  :tests
validates :name, :uniqueness => true
validates :name, :presence => true

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to  :test
  has_many  :answers
  # has_many :responses
 has_and_belongs_to_many :responses
  

validates :question,:type_of_question, :presence => true
 
end

app/models/response.rb
class Response < ActiveRecord::Base
   belongs_to  :test
   belongs_to  :user
   belongs_to  :question
   has_and_belongs_to_many :question
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many  :users
end

app/models/samgruff.rb
class Samgruff < ActiveRecord::Base
end

app/models/test.rb
class Test< ActiveRecord::Base
  belongs_to  :category
  has_many :questions, :dependent => :destroy
  has_many :responses
  validates :name,:no_of_questions, :presence => true
  validates :name, :uniqueness => true
  validates :no_of_questions,:numericality => { :only_integer => true }
  validates :category_id, :presence => true
  # :scope => [:category_category_id],
  # validate :my_validation_method
  # def my_validation_method
  #  if self.category_id == "Please Select"
  #    errors.add(:category_id, "You are crazy")
  #    return false
  #  end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :role
  acts_as_authentic do |c|
    has_many :responses

#    c.transition_from_crypto_providers = Authlogic::CryptoProviders::MD5
#    c.crypto_provider = Authlogic::CryptoProviders::Sha1
#   c.validate_email_field = false
#    c.require_password_confirmation = false
#    c.ignore_blank_passwords = true
#    c.validate_password_field = false
    #c.validate_password_field = false
#    c.validate_email_field = false
    validates :first_name,:last_name,:email,:phone_number,:presence => true
    validates :password_confirmation ,:presence => true ,:on=>:create
    #validates :email, :email_format => true
    validates :email, :uniqueness => true
    validates :phone_number, :numericality => { :only_integer => true }
    validates :phone_number, :length => {:is => 10}
    validates :password, :presence =>true, :length => { :minimum => 6, :maximum => 20 },:on=>:create

#    validates :password,:length => {:within => 8..16}
    #c.my_config_option = my_value # for available options see documentation in: Authlogic::ActsAsAuthentic
  end  # block optional

#  def send_forgot_password!
##  deactivate!
#  reset_perishable_token!
#  Notifier.forgot_password(self).deliver
#end

  def self.user_create(params_user, current_user)
    
  new(params_user.merge!({:role_id => current_user.is_admin ? 2 : 3, :created_user_id => current_user.id}))
    #new(params_user.merge!({:role_id => 3, :created_user_id => 1}))
  end
#    @user.password  = "test123"
#    @user.password_confirmation  = "test123"

  scope :temp_scope , :conditions => {:role_id => [1,2,3]}
  def self.user_findout_user(current_user)
   self.where("role_id = ? and  created_user_id = ?","3", current_user.id)
  end
 
#@posts = Post.where(["created_at >= ?", Time.current])
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  #validates :email,:password ,:presence =>true
  #   validates :first_name,:last_name,:email,:phone_number,:password,:password_confirmation ,:presence => true
   
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.order("id").page(params[:page]).per(10)
    @categories =Category.all
    
  end
  
  def new
    @test=Test.new
  end

  def create
    @test = Test.new(params[:test])    
    if @test.save
     flash[:notice] = "test Created"
      redirect_to new_test_question_path(@test)
    else
      render  "new"
    end
  end

  def show
     @test= Test.find(params[:id])
     # .order("id").page(params[:page]).per(10)
  end


  def edit
    @test= Test.find(params[:id])
  end

  def update    
    @test = Test.find(params[:id])
    if @test.update_attributes(params[:test])
      redirect_to edit_test_question_path(@test)
    else
      render :action=> "edit"
    end
  end

  def destroy
    @test= Test.find(params[:id])
    @test.destroy
    redirect_to tests_path 
  end

  def show
    @test = Test.find(params[:id])
  end
  def tests_normal_show

# raise params.inspect 
selected_cat_id =params[:id] 
 @tests= Test.where("category_id=?", selected_cat_id) 
#    raise  @category.id.inspect 
end
  # def report
#     
    # for questions in @test.questions
# 
      # if questions.type_of_question =="radio"
      # eval =Evaluate.new(:selected_answer => :answer.selctedvalue) 
     # end
#      
   # end
    #@test=Test.all
    #raise @test.inspect
    
  #  @evaluate = Evaluate.new(params[:id])
   # raise @evaluate.inspect
    
   # if @evaluate.save
      
    #end
    
    # raise params.inspect;
  # end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_filter :require_no_user, :only => [:new, :create]
  #before_filter :require_user, :only => [:show, :edit, :update]
  
  def index
    
    if current_user.is_admin
      @users = User.temp_scope
    else
      @users = User.user_findout_user(current_user)
    end

  end

  def show
    @user=current_user
  end

  def new   
    @user = User.new
  end
  
  def create
    puts "-------------- #{current_user}"
    @user = User.user_create(params[:user], current_user) #new(params[:user])
    if @user.save      
      flash[:notice] = "Account registered!"
      redirect_to users_path      
    else
      render :action => :new
    end
  end

  def edit
    @user = current_user 
  end
  
  def update
    
    @user = User.find_by_id(params[:id])
    puts "&&&&&&&& in controller before  post #{@user.first_name.inspect}"
    if @user.update_attributes!(params[:user])
      flash[:notice] = "Account updated!"
      puts "********** in controller after post #{@user.first_name.inspect}"
      redirect_to user_path(current_user)
    else
      render :action => :edit
    end
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper

    def display_answer(question) 
    if @response_count.nil? 
      local_count = 1 
    else 
     local_count=@response_count.no_of_attempts

    end

   response = Response.where("test_id=? and question_id =? and no_of_attempts = ? ",@test.id ,question.id,local_count).first

   if response.nil?

     image_tag("/images/wrong.png")

    else 
     
      response.is_correct? ?image_tag("/images/tick.png") : image_tag("/images/wrong.png")

   end 
  end 
end

app/helpers/samgruffs_helper.rb
module SamgruffsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<table>
	<tr>
		<td><%= form.label :first_name %></td>
		<td><%= form.text_field :first_name,:size=>15 %></td>
	</tr>
	<tr>
		<td><%= form.label :last_name %></td>
		<td><%= form.text_field :last_name,:size=>15 %></td>
	</tr>
	<tr>
		<td><%= form.label :email %></td>
		<td><%= form.text_field :email,:size=>15 %></td>
	</tr>
	<tr>
		<td><%= form.label :phone_number %></td>
		<td><%= form.text_field :phone_number,:size=>15 %></td>
	</tr>
	<%# if !@user%>
	<tr>
		<td><%= form.label :password, form.object.new_record? ? nil : "Change password" %></td>
		<td><%= form.password_field :password,:size=>15 %></td>
	</tr>
	<tr>
		<td><%= form.label :password_confirmation %></td>
		<td><%= form.password_field :password_confirmation,:size=>15 %></td>
	</tr>
	<%#end%>
</table>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>

 <%= render :partial => "form", :object => f %>
 
 <%= f.submit %>

 
<% end %>

app/views/users/index.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<div id="left_navigation_show" align="left" style="border:solid;float:left;width:17.5%;height:100%;padding-top:50px;padding-left:10px;" >
<a href="">Questionaire</a><br /><br />
<a href="http://www....">Surveys</a><br /><br />
<a href="http://www....">Add Administration</a><br /><br />

</div>
<div id="show_content" align="middle" style="border:solid;float:right;width:80.5%;height:100%;"  >
<h1>Listing users</h1>
<table  >
    <tr >
        <th>
            First Name
        </th>
        <th>
            Last Name
        </th>
        <th>
            Email
        </th>

        <th>
            Phone number
        </th>
    </tr>
    <% @users.each do |user| %>
    <tr>
        <td>
            <%= user.first_name %>
        </td>
        <td>
            <%= user.last_name %>
        </td>
        <td>
            <%= user.email %>
        </td>
	<td>
	    <%= user.phone_number%>
	</td>
     </tr>
    <% end %>
</table>
</div>

app/views/users/index.html.erb
<!DOCTYPE html>
<html>
	<body id="body">

		
			<h1>Listing of Administrators</h1>
                        <%= link_to "New User", new_user_path %><br/><br/>
                        
			<table  >
				<tr >
					<th> First Name </th>
					<th> Last Name </th>
					<th> Email </th>
                                        <th> Role </th>
					<th> Phone number </th>
				</tr>
				<% @users.each do |user| %>                          
				<tr>
					<td> <%= user.first_name %> </td>
					<td> <%= user.last_name %> </td>
					<td> <%= user.email %> </td>
                                        <td> <%= user.role.name%> </td>
					<td> <%= user.phone_number%> </td>
				</tr>
				<% end %>
			</table>
		
	</body>
</html>

app/views/users/new.html.erb
 <!DOCTYPE html>
<html>
	<head>
		<title>Trunk</title>
		<%= stylesheet_link_tag   "login" %>
		<%= javascript_include_tag "login" %>
		<%= csrf_meta_tags %>
	</head>
    <body id="body">

        <div id="reg_form">
            <h3> Registration Form</h3>
            <%= form_for@user,:validate=>true do |f| %>
            <%#= f.error_messages %>
            <%= render :partial => "form", :object => f %>
            <%= f.submit "Register" %>
            <% end %>
        </div>
    </body>
</html>

app/views/users/show.html.erb
  
<table border="1"  class="table     1">
  

 <thead>
        <tr>
            
            <th scope="col" abbr="FirstName">First Name</th>
            <th scope="col" abbr="LastName">Last Name</th>
            <th scope="col" abbr="E-mail">E-mail</th>
            <th scope="col" abbr="PhoneNumber">Phone Number</th>
        </tr>
    </thead>

    <tbody>
        <tr>

            <td><%= @user.first_name%></td>
            <td><%= @user.last_name%></td>
            <td><%= @user.email%></td>
            <td><%= @user.phone_number%></td>
        </tr>
    </tbody>

</table>
</ br>

  

  <div class="linksForProfile"  style="width:212px; padding-top:20px " >
    <a href="/users/edit/edit" style="width: 50px;">edit</a>
    
     <%#= link_to "edit2" , style="width: 50px;",edit_user_path %>   &nbsp;&nbsp;&nbsp;&nbsp;

     <a href=<%= reset_password_path  %>>Change Password</a>

  </div>