config/routes.rb
Trunk::Application.routes.draw do
  root :to => 'user_sessions#login'
  
  match 'login' => "user_sessions#login",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout
  match 'tests_normal_show/:id' => "tests#tests_normal_show", :as => "tests_normal_show" ,:via => :get
  match'forgot_password'=>'signup#forgot_password',:as=> "forgot_password" ,:via =>[:get,:post]
  match'reset_password'=>'signup#reset_password',:as =>"reset_password" ,:via =>[:get,:post]
   match'graph'=>'samgruffs#index',:as=>"graph",:via=>:get
  match'report'=>'responses#report',:as=> "report" ,:via => :put
  match 'samgruffs/graph_code' => "samgruffs#graph_code", :via => :get
  match 'samgruffs/index' => "samgruffs#index", :via => :get
  resources :signup
  resources :users
  resources :user_sessions
  resources :tests do
    resources :questions do
      resources :answers
    end
  end
  resources :categories

  resources :reponses

  

end

app/models/admin_session.rb
class AdminSession < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base

#  validates :answer, :presence => true
end

app/models/category.rb
class Category < ActiveRecord::Base
 has_many  :tests
validates :name, :uniqueness => true
validates :name, :presence => true

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  belongs_to :question
end

app/models/group.rb
class Group < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to  :test
  has_many  :answers
  # has_many :responses
 has_and_belongs_to_many :responses
  

validates :question,:type_of_question, :presence => true
 
end

app/models/response.rb
class Response < ActiveRecord::Base
   belongs_to  :test
   belongs_to  :user
   belongs_to  :question
   has_and_belongs_to_many :question
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_many  :users
end

app/models/samgruff.rb
class Samgruff < ActiveRecord::Base
end

app/models/test.rb
class Test< ActiveRecord::Base
  belongs_to  :category
  has_many :questions, :dependent => :destroy
  has_many :responses
  validates :name,:no_of_questions, :presence => true
  validates :name, :uniqueness => true
  validates :no_of_questions,:numericality => { :only_integer => true }
  validates :category_id, :presence => true
  # :scope => [:category_category_id],
  # validate :my_validation_method
  # def my_validation_method
  #  if self.category_id == "Please Select"
  #    errors.add(:category_id, "You are crazy")
  #    return false
  #  end
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to  :role
  acts_as_authentic do |c|
    has_many :responses

#    c.transition_from_crypto_providers = Authlogic::CryptoProviders::MD5
#    c.crypto_provider = Authlogic::CryptoProviders::Sha1
#   c.validate_email_field = false
#    c.require_password_confirmation = false
#    c.ignore_blank_passwords = true
#    c.validate_password_field = false
    #c.validate_password_field = false
#    c.validate_email_field = false
    validates :first_name,:last_name,:email,:phone_number,:presence => true
    validates :password_confirmation ,:presence => true ,:on=>:create
    #validates :email, :email_format => true
    validates :email, :uniqueness => true
    validates :phone_number, :numericality => { :only_integer => true }
    validates :phone_number, :length => {:is => 10}
    validates :password, :presence =>true, :length => { :minimum => 6, :maximum => 20 },:on=>:create

#    validates :password,:length => {:within => 8..16}
    #c.my_config_option = my_value # for available options see documentation in: Authlogic::ActsAsAuthentic
  end  # block optional

#  def send_forgot_password!
##  deactivate!
#  reset_perishable_token!
#  Notifier.forgot_password(self).deliver
#end

  def self.user_create(params_user, current_user)
    
  new(params_user.merge!({:role_id => current_user.is_admin ? 2 : 3, :created_user_id => current_user.id}))
    #new(params_user.merge!({:role_id => 3, :created_user_id => 1}))
  end
#    @user.password  = "test123"
#    @user.password_confirmation  = "test123"

  scope :temp_scope , :conditions => {:role_id => [1,2,3]}
  def self.user_findout_user(current_user)
   self.where("role_id = ? and  created_user_id = ?","3", current_user.id)
  end
 
#@posts = Post.where(["created_at >= ?", Time.current])
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
  #validates :email,:password ,:presence =>true
  #   validates :first_name,:last_name,:email,:phone_number,:password,:password_confirmation ,:presence => true
   
  # configuration here, see documentation for sub modules of Authlogic::Session
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_remove_fields(name, f)
    f.hidden_field(:_destroy) + link_to_function(name, "remove_fields(this)")
  end
  
  def link_to_add_fields(name, f, association)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render(association.to_s.singularize + "_fields", :f => builder)
    end
    link_to_function(name, "add_fields(this, \"#{association}\", \"#{escape_javascript(fields)}\")")
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/responses_helper.rb
module ResponsesHelper

    def display_answer(question) 
    if @response_count.nil? 
      local_count = 1 
    else 
     local_count=@response_count.no_of_attempts

    end

   response = Response.where("test_id=? and question_id =? and no_of_attempts = ? ",@test.id ,question.id,local_count).first

   if response.nil?

     image_tag("/images/wrong.png")

    else 
     
      response.is_correct? ?image_tag("/images/tick.png") : image_tag("/images/wrong.png")

   end 
  end 
end

app/helpers/samgruffs_helper.rb
module SamgruffsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Trunk</title>
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag  :defaults,"application.js","rails.validations", "rails.validations.custom","http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js","create.rjs","rails.validations.custom.js","jquery-1.7.1.js","tabs.js","categories.js.coffee","tabs.js","rails.js"%>
		<%#= javascript_include_tag :defaults,"application","rails.validations", "rails.validations.custom" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<div id="wrapper">
			<div id="header">
				<h1>Dynamic Form Builder</h1>
			</div>
			<div id="sessions" >
				<div class="left">
					Welcome <%= current_user.first_name %> <%= current_user.last_name %> !
				</div>
				<div class="right">
					<%= button_to '' , logout_path, :method => :delete , :class=>"logout" %>
				</div>
			</div>
			<div id="navigator">
				
					<% if current_user.is_admin? || current_user.role.name  == "Administrator" %>
					<ul><li>
						<a href=<%= users_path  %>>Users</a>
					</li></ul>
					<% end %>

					<% if current_user.role_id != 1  %>
					<ul><li>
						<a href=<%= tests_path  %>>Tests</a>
					</li>
					<li>
						<a href=<%= edit_user_path  %>>My Profile</a>
					</li>
                                       
					</ul>
					
					<% end %>
				
			</div>
			<div id="main">
				<%= yield %>
			</div>
			<div class="spacerdiv"></div>
		</div>
	</body>
</html>

app/views/notifier/forgot_password.erb
<%#
# To change this template, choose Tools | Templates
# and open the template in the editor.
%>

<%= "forgot_password" %>
Here's a link to reset your password

<%#http://localhost:3004/signup/reset_password%>

<%= @reset_password_link %>